services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "cultureamp/backstage-cdk-assets"]
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
