#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

function main(){
  local dest; dest="$(plugin_read_config "DEST" "./ops")"
  dest="${dest}/.backstage"

  rm -rf ${dest}
  mkdir -p ${dest}
  cp catalog-info*.y*ml ${dest}
}

main "$@"
