#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

function main(){
  local source; source="$(plugin_read_config "SOURCE" "./")"
  local dest; dest="$(plugin_read_config "DEST" "./ops")"

  source="$(cleanPath "${source}")catalog-info*.y*ml"
  dest="$(cleanPath "${dest}").backstage"

  rm -rf "${dest}"
  mkdir -p "${dest}"
  cp ${source} ${dest}
}

function cleanPath() {
  local dir=$1

  if [[ "${dir}" != ./* ]]; then
    dir="./${dir}"
  fi

  if [[ "${dir}" != */ ]]; then
    dir="${dir}/"
  fi

  echo "${dir}"
}

main "$@"
